[build]
  base = "ui"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Optional: Configure redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
